/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 회원가입 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description 사용자 이메일
                         * @example test@tbc.com
                         */
                        email: string;
                        /**
                         * @description 사용자 닉네임
                         * @example 데품타
                         */
                        nickname: string;
                        /**
                         * @description 비밀번호 (8자 이상, 영문과 숫자 조합)
                         * @example Test1234
                         */
                        password: string;
                        /**
                         * @description 비밀번호 확인
                         * @example Test1234
                         */
                        confirmPassword: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 사용자 로그인 (중복 로그인 시 자동으로 다른 기기 로그아웃) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description 사용자 이메일
                         * @example test@tbc.com
                         */
                        email: string;
                        /**
                         * @description 비밀번호
                         * @example Test1234
                         */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            accessToken: string;
                            refreshToken: string;
                            /** @description 첫 로그인 여부 (true: 최초 로그인, false: 재로그인) */
                            isFirstLogin: boolean;
                            /** @description 중복 로그인 여부 (true: 다른 기기에서 로그아웃됨, false: 일반 로그인) */
                            isDuplicateLogin: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 사용자 로그아웃 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 액세스 토큰 갱신 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description 리프레시 토큰
                         * @example eyJhbGciOi...
                         */
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            accessToken: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signup/check-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 이메일 중복 확인 */
        get: {
            parameters: {
                query: {
                    /**
                     * @description 확인할 이메일
                     * @example test@tbc.com
                     */
                    email: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            /** @description 이메일 사용 가능 여부 (true: 사용 가능, false: 중복) */
                            available: boolean;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signup/check-nickname": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 닉네임 중복 확인 */
        get: {
            parameters: {
                query: {
                    /**
                     * @description 확인할 닉네임
                     * @example 데품타
                     */
                    nickname: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            /** @description 닉네임 사용 가능 여부 (true: 사용 가능, false: 중복) */
                            available: boolean;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tech-stacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 기술 스택 검색 */
        get: {
            parameters: {
                query?: {
                    /** @description 검색 키워드 */
                    keyword?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            results: {
                                /** @description 기술 스택 ID */
                                id: number;
                                /** @description 기술 스택 이름 */
                                name: string;
                                /**
                                 * Format: date-time
                                 * @description 날짜 및 시간 (ISO 8601 형식)
                                 */
                                createdAt: string;
                                /**
                                 * Format: date-time
                                 * @description 날짜 및 시간 (ISO 8601 형식)
                                 */
                                updatedAt: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        /** @description 기술 스택 추가 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 기술 스택 이름 */
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 성공 메시지 */
                            message: string;
                            techStack: {
                                /** @description 기술 스택 ID */
                                id: number;
                                /** @description 기술 스택 이름 */
                                name: string;
                                /**
                                 * Format: date-time
                                 * @description 날짜 및 시간 (ISO 8601 형식)
                                 */
                                createdAt: string;
                                /**
                                 * Format: date-time
                                 * @description 날짜 및 시간 (ISO 8601 형식)
                                 */
                                updatedAt: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/file/presigned-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 이미지 업로드를 위한 Presigned URL 발급 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description 업로드할 파일 이름 (예: image.jpg)
                         * @example profile.jpg
                         */
                        fileName: string;
                        /**
                         * @description 파일의 MIME 타입
                         * @example image/jpeg
                         */
                        contentType: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 파일 업로드용 Presigned URL */
                            presignedUrl: string;
                            /** @description S3 버킷 내 파일 키 */
                            key: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 회원 정보 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            email: string;
                            nickname: string;
                            profile?: {
                                career: string;
                                purpose: ("취업 준비" | "이직 준비" | "단순 개발 역량 향상" | "회사 내 프로젝트 원활하게 수행") | {
                                    /** @enum {string} */
                                    type: "기타";
                                    detail: string;
                                };
                                goal?: string;
                                techStacks: string[];
                                profileImage?: string;
                            };
                        };
                    };
                };
            };
        };
        /** @description 회원 정보 수정 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        nickname?: string;
                        /** @enum {string} */
                        career?: "경력 없음" | "0 - 3년" | "4 - 7년" | "8 - 10년" | "11년 이상";
                        purpose?: ("취업 준비" | "이직 준비" | "단순 개발 역량 향상" | "회사 내 프로젝트 원활하게 수행") | {
                            /** @enum {string} */
                            type: "기타";
                            detail: string;
                        };
                        goal?: string;
                        techStacks?: string[];
                        profileImage?: string;
                        password?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                        };
                    };
                };
            };
        };
        /** @description 프로필 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        career: "경력 없음" | "0 - 3년" | "4 - 7년" | "8 - 10년" | "11년 이상";
                        purpose: ("취업 준비" | "이직 준비" | "단순 개발 역량 향상" | "회사 내 프로젝트 원활하게 수행") | {
                            /** @enum {string} */
                            type: "기타";
                            detail: string;
                        };
                        goal?: string;
                        techStacks: string[];
                        profileImage?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 활성화된 타이머 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 타이머 ID */
                            timerId: string;
                            /** @description 학습 기록 ID */
                            studyLogId: string;
                            splitTimes: {
                                /**
                                 * Format: date-time
                                 * @description 날짜 및 시간 (ISO 8601 형식)
                                 */
                                date: string;
                                /** @description 소요 시간 (초) */
                                timeSpent: number;
                            }[];
                            /**
                             * Format: date-time
                             * @description 날짜 및 시간 (ISO 8601 형식)
                             */
                            startTime: string;
                            /**
                             * Format: date-time
                             * @description 마지막 업데이트 시간 (업데이트 전에는 null)
                             */
                            lastUpdateTime: string | null;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @description 에러 메시지 */
                                message: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** @description 타이머 시작 (오늘의 목표 생성 포함) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 오늘의 목표 (30자 이내) */
                        todayGoal: string;
                        tasks?: string[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 성공 메시지 */
                            message: string;
                            /** @description 생성된 학습 기록 ID */
                            studyLogId: string;
                            /** @description 생성된 타이머 ID */
                            timerId: string;
                            /**
                             * Format: date-time
                             * @description 날짜 및 시간 (ISO 8601 형식)
                             */
                            startTime: string;
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @description 에러 메시지 */
                                message: string;
                            };
                            data: {
                                /** @description 이미 실행 중인 타이머 ID */
                                timerId: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timers/{timerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description 타이머 상태 업데이트 (10분마다) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 타이머 ID */
                    timerId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        splitTimes: {
                            /**
                             * Format: date-time
                             * @description 날짜 및 시간 (ISO 8601 형식)
                             */
                            date: string;
                            /** @description 소요 시간 (초) */
                            timeSpent: number;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 성공 메시지 */
                            message: string;
                            /**
                             * Format: date-time
                             * @description 날짜 및 시간 (ISO 8601 형식)
                             */
                            startTime: string;
                            splitTimes: {
                                /**
                                 * Format: date-time
                                 * @description 날짜 및 시간 (ISO 8601 형식)
                                 */
                                date: string;
                                /** @description 소요 시간 (초) */
                                timeSpent: number;
                            }[];
                            /**
                             * Format: date-time
                             * @description 날짜 및 시간 (ISO 8601 형식)
                             */
                            lastUpdateTime: string;
                        };
                    };
                };
            };
        };
        post?: never;
        /** @description 타이머 삭제/초기화 (타이머와 관련된 목표, 할 일, 회고 모두 삭제) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 타이머 ID */
                    timerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 성공 메시지 */
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @description 에러 메시지 */
                                message: string;
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timers/{timerId}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 타이머 종료 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 타이머 ID */
                    timerId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        splitTimes: {
                            /**
                             * Format: date-time
                             * @description 날짜 및 시간 (ISO 8601 형식)
                             */
                            date: string;
                            /** @description 소요 시간 (초) */
                            timeSpent: number;
                        }[];
                        /** @description 회고 내용 (15자 이상) */
                        review: string;
                        tasks: {
                            /** @description 할 일 내용 (30자 이내) */
                            content: string;
                            /** @description 완료 여부 */
                            isCompleted: boolean;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 성공 메시지 */
                            message: string;
                            /** @description 총 학습 시간 (초) */
                            totalTime: number;
                            /**
                             * Format: date-time
                             * @description 날짜 및 시간 (ISO 8601 형식)
                             */
                            endTime: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{studyLogId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description 타이머 진행 중일때 할 일 목록 전체 업데이트 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 학습 기록 ID */
                    studyLogId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        tasks: {
                            /** @description 할 일 내용 (30자 이내) */
                            content: string;
                            /** @description 완료 여부 */
                            isCompleted: boolean;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 성공 여부 */
                            success: boolean;
                            /** @description 응답 메시지 */
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @description 에러 메시지 */
                                message: string;
                            };
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @description 에러 메시지 */
                                message: string;
                            };
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 사용자의 공부 기록 통계 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 연속 공부 일수 */
                            consecutiveDays: number;
                            /** @description 총 공부 시간(초) */
                            totalStudyTime: number;
                            /** @description 일 평균 공부 시간(초) */
                            averageDailyStudyTime: number;
                            /** @description 목표 달성률(%) */
                            taskCompletionRate: number;
                            weekdayStudyTime: {
                                /** @description 월요일 평균 공부 시간(초) */
                                Monday: number;
                                /** @description 화요일 평균 공부 시간(초) */
                                Tuesday: number;
                                /** @description 수요일 평균 공부 시간(초) */
                                Wednesday: number;
                                /** @description 목요일 평균 공부 시간(초) */
                                Thursday: number;
                                /** @description 금요일 평균 공부 시간(초) */
                                Friday: number;
                                /** @description 토요일 평균 공부 시간(초) */
                                Saturday: number;
                                /** @description 일요일 평균 공부 시간(초) */
                                Sunday: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 학습 히트맵 데이터 조회 (바다) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            heatmap: {
                                /** @description 날짜 (YYYY-MM-DD) */
                                date: string;
                                /** @description 학습 시간 (시간 단위) */
                                studyTimeHours: number;
                                /** @description 색상 레벨 (0-5) */
                                colorLevel: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 총 학습 시간 또는 일 평균 학습 시간을 기준으로 정렬된 랭킹을 조회합니다.
         * @description 전체 유저의 학습 시간 랭킹 조회
         */
        get: {
            parameters: {
                query?: {
                    /** @description 정렬 기준 (total: 총 학습 시간, avg: 일 평균 학습 시간) */
                    sortBy?: "total" | "avg";
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            data: {
                                rankings: {
                                    /** @description 순위 */
                                    rank: number;
                                    /** @description 사용자 ID */
                                    userId: string;
                                    /** @description 닉네임 */
                                    nickname: string;
                                    /** @description 총 학습 시간 (초) */
                                    totalStudyTime: number;
                                    /** @description 일 평균 학습 시간 (초) */
                                    averageStudyTime: number;
                                    profile: {
                                        /** @enum {string} */
                                        career: "경력 없음" | "0 - 3년" | "4 - 7년" | "8 - 10년" | "11년 이상";
                                        purpose: ("취업 준비" | "이직 준비" | "단순 개발 역량 향상" | "회사 내 프로젝트 원활하게 수행") | {
                                            /** @enum {string} */
                                            type: "기타";
                                            detail: string;
                                        };
                                        profileImage: string | null;
                                        techStacks: {
                                            /** @description 기술 스택 ID */
                                            id: number;
                                            /** @description 기술 스택 이름 */
                                            name: string;
                                        }[];
                                    };
                                }[];
                                pagination: {
                                    /** @description 현재 페이지 번호 */
                                    currentPage: number;
                                    /** @description 전체 페이지 수 */
                                    totalPages: number;
                                    /** @description 전체 항목 수 */
                                    totalItems: number;
                                    /** @description 다음 페이지 존재 여부 */
                                    hasNext: boolean;
                                    /** @description 이전 페이지 존재 여부 */
                                    hasPrev: boolean;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 학습 기록 목록을 조회합니다. 페이지네이션과 날짜 필터링을 지원합니다. */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    /** @description 날짜 (YYYY-MM-DD 형식) */
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            data: {
                                studyLogs: {
                                    /** @description 학습 기록 ID */
                                    id: string;
                                    /**
                                     * Format: date
                                     * @description 날짜 (YYYY-MM-DD 형식)
                                     */
                                    date: string;
                                    /** @description 오늘의 목표 */
                                    todayGoal: string;
                                    /** @description 학습 시간 (초) */
                                    studyTime: number;
                                    /** @description 전체 할 일 개수 */
                                    totalTasks: number;
                                    /** @description 미완료 할 일 개수 */
                                    incompleteTasks: number;
                                    /** @description 완료율 (%) */
                                    completionRate: number;
                                }[];
                                pagination: {
                                    /** @description 현재 페이지 번호 */
                                    currentPage: number;
                                    /** @description 전체 페이지 수 */
                                    totalPages: number;
                                    /** @description 전체 항목 수 */
                                    totalItems: number;
                                    /** @description 다음 페이지 존재 여부 */
                                    hasNext: boolean;
                                    /** @description 이전 페이지 존재 여부 */
                                    hasPrev: boolean;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study-logs/{studyLogId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 특정 학습 기록의 상세 정보를 조회합니다. 할 일 목록, 학습 시간, 회고 등을 포함합니다. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 학습 기록 ID */
                    studyLogId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            data: {
                                /** @description 학습 기록 ID */
                                id: string;
                                /**
                                 * Format: date
                                 * @description 날짜 (YYYY-MM-DD 형식)
                                 */
                                date: string;
                                /** @description 오늘의 목표 */
                                todayGoal: string;
                                /** @description 학습 시간 (초) */
                                studyTime: number;
                                tasks: {
                                    /** @description 할 일 ID */
                                    id: string;
                                    /** @description 할 일 내용 */
                                    content: string;
                                    /** @description 완료 여부 */
                                    isCompleted: boolean;
                                }[];
                                /** @description 회고 */
                                review: string;
                                /** @description 완료율 (%) */
                                completionRate: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @description 학습 기록과 관련된 모든 데이터(할 일, 타이머, 회고)를 삭제합니다. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 학습 기록 ID */
                    studyLogId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 성공 여부 */
                            success: boolean;
                            /** @description 응답 메시지 */
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
