services:
  mysql:
    image: mysql:8
    container_name: devtime-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: devtime
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - devtime-data:/var/lib/mysql

volumes:
  devtime-data:
